name: Daily Update Workflow

on:
  push:
    branches:
      - main

jobs:
  modify_labels:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Modify labels.json using Python script
        run: |
          python scrape.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          
          git add labels.json
          git commit -m "daily update of labels.json"
          git push